import streamlit as st

# ---------------------- PAGE CONFIG ----------------------
st.set_page_config(
    page_title="MedFusion-AI",
    page_icon="🧠",
    layout="wide"
)

# ---------------------- HEADER ----------------------
st.title("🧠 MedFusion-AI")
st.subheader("A Multimodal Medical AI Assistant (For Educational Use Only)")

st.info(
    "⚠️ **Important Notice**\n"
    "- This system is designed for *learning and research* purposes only.\n"
    "- It does **not** diagnose diseases or replace medical professionals.\n"
    "- All outputs are generated by AI models trained on limited datasets.\n"
    "- Always verify findings with a qualified doctor."
)

# ---------------------- INTRODUCTION ----------------------
st.markdown("""
MedFusion-AI integrates **three intelligent pipelines** into one unified assistant:

### 🔍 1. PubMed Research Assistant (Text RAG)
Retrieves scientific literature using PubMed + FAISS  
and generates grounded answers using **Llama-3.1-8B (Ollama)**.

### 🖼️ 2. Image Assistant (MedMNIST Vision Models)
Performs educational image analysis using custom-trained **ResNet-18** models on:
- ChestMNIST  
- PneumoniaMNIST  
- BreastMNIST  
- OrganAMNIST  

Outputs are **contextualized and explained** by the LLM.

### 📄 3. PDF Report Assistant
Extracts text from medical PDFs  
and generates simple, safe explanations with optional follow-up Q&A  
using RAG + LLM (late fusion).

---

## 🚀 **How to Use**
Use the **left sidebar** to navigate between:
- 🖼️ Image Assistant  
- 📄 Report Assistant  
- 📚 Text RAG Assistant  

Each tool runs independently but follows the same principles:
- Safety checks  
- Scientific grounding  
- Non-diagnostic explanations  
- LLM-based clarification  
""")

# ---------------------- FOOTER ----------------------
st.markdown("---")
st.caption(
    "MedFusion-AI • A student research project integrating PubMed RAG, MedMNIST vision models, "
    "and local LLMs for safe educational assistance."
)
