import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT_DIR))



import streamlit as st
from PIL import Image

from Backend.vision.inference import (
    predict_chest_from_pil,
    predict_pneumonia_from_pil,
    predict_breast_from_pil,
    predict_organ_from_pil
)

st.title("🖼️ Image Assistant")
st.caption("AI-based image analysis for educational purposes only.")

model_choice = st.selectbox(
    "Choose Vision Model",
    [
        "ChestMNIST (Multi-label X-ray)",
        "Pneumonia Detection",
        "Breast Cancer Classification",
        "Organ Classification (CT)"
    ]
)

uploaded = st.file_uploader(
    "Upload medical image (PNG / JPG)",
    type=["png", "jpg", "jpeg"]
)

if uploaded:
    image = Image.open(uploaded).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    if st.button("Run Analysis"):
        with st.spinner("Running model..."):

            if model_choice.startswith("Chest"):
                result = predict_chest_from_pil(image)
                st.subheader("ChestMNIST Results")
                st.json(result)

            elif model_choice.startswith("Pneumonia"):
                result = predict_pneumonia_from_pil(image)
                st.subheader("Pneumonia Prediction")
                st.json(result)

            elif model_choice.startswith("Breast"):
                result = predict_breast_from_pil(image)
                st.subheader("Breast Cancer Prediction")
                st.json(result)

            elif model_choice.startswith("Organ"):
                result = predict_organ_from_pil(image)
                st.subheader("Organ Classification")
                st.json(result)

        st.warning(
            "⚠️ Results are generated by AI for learning purposes only "
            "and must not be used for medical decisions."
        )
